name: Deploy to Azure Web App

on:
  push:
    branches:
      - master  # or 'main' depending on your default branch name

env:
  AZURE_WEBAPP_NAME: real-estate-docker    # This is correct
  DOCKER_HUB_USERNAME: ryanle3             # This is correct
  IMAGE_NAME: real-estate-app              # This is correct

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Export Secrets to .env.production
      run: |
        touch .env.production
        for secret_name in $(echo '${{ toJSON(secrets) }}' | jq -r 'keys[]' | grep '^ENV_'); 
        do echo "${secret_name#ENV_}=${!secret_name}" >> .env.production
        done
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
